"""
Module 5: ER Diagram Generator
Responsibility: Render the ER model as a professional diagram using Graphviz.

Diagram conventions:
  - Entities    → rectangle nodes (filled, bold label)
  - Attributes  → ellipse nodes (lighter fill)
  - PK attrs    → underlined label inside ellipse
  - FK attrs    → dashed border ellipse
  - Relationships → diamond nodes on edges (Chen notation)
  - Cardinality → edge labels (1, N, M)

Output formats: PNG (default), PDF, SVG
"""

import os
from graphviz import Digraph


# Colour palette
COLOUR = {
    "entity_fill":   "#2C3E50",
    "entity_font":   "white",
    "entity_border": "#1A252F",
    "attr_fill":     "#ECF0F1",
    "attr_border":   "#BDC3C7",
    "pk_fill":       "#F39C12",
    "pk_font":       "white",
    "fk_fill":       "#D5E8D4",
    "fk_border":     "#82B366",
    "rel_fill":      "#D6EAF8",
    "rel_border":    "#2980B9",
    "junction_fill": "#FADBD8",
    "junction_border":"#E74C3C",
}


class ERDiagramGenerator:
    """Generates Graphviz-based ER diagrams from an ER model dict."""

    def generate(
        self,
        er_model: dict,
        output_path: str = "er_diagram",
        fmt: str = "png",
        view: bool = False,
        notation: str = "chen",   # "chen" or "crow"
    ) -> str:
        """
        Parameters
        ----------
        er_model    : dict  — from ERModelBuilder.build()
        output_path : str   — file path without extension
        fmt         : str   — output format (png / pdf / svg)
        view        : bool  — open diagram after generation
        notation    : str   — "chen" (classic) or "crow" (crow's foot labels)

        Returns
        -------
        str : absolute path to generated diagram file
        """
        dot = Digraph(
            name="ER_Diagram",
            comment="Generated by Enhanced Hybrid AI DB Engine",
        )
        dot.attr(rankdir="LR", splines="ortho", nodesep="0.8", ranksep="1.2",
                 fontname="Helvetica", bgcolor="white")

        entities  = er_model.get("entities", {})
        rels      = er_model.get("relationships", [])
        junctions = er_model.get("junction_tables", {})

        # ── Draw Entities and their Attributes ─────────────────────────
        for ent_name, ent_data in entities.items():
            pk   = ent_data.get("primary_key")
            fk_cols = {fk["column"] for fk in ent_data.get("foreign_keys", [])}
            attrs = ent_data.get("attributes", [])

            with dot.subgraph(name=f"cluster_{ent_name}") as sg:
                sg.attr(style="invis")

                # Entity box
                sg.node(
                    ent_name,
                    label=ent_name,
                    shape="box",
                    style="filled,bold",
                    fillcolor=COLOUR["entity_fill"],
                    fontcolor=COLOUR["entity_font"],
                    color=COLOUR["entity_border"],
                    fontname="Helvetica-Bold",
                    fontsize="13",
                )

                # Attribute ellipses
                for attr in attrs:
                    attr_node_id = f"{ent_name}__{attr}"
                    is_pk = (attr == pk)
                    is_fk = (attr in fk_cols)

                    label    = f"<<u>{attr}</u>>" if is_pk else attr
                    fill     = COLOUR["pk_fill"] if is_pk else (COLOUR["fk_fill"] if is_fk else COLOUR["attr_fill"])
                    font     = COLOUR["pk_font"] if is_pk else "black"
                    style    = "filled,dashed" if is_fk and not is_pk else "filled"
                    border   = COLOUR["fk_border"] if is_fk else COLOUR["attr_border"]

                    sg.node(
                        attr_node_id,
                        label=label,
                        shape="ellipse",
                        style=style,
                        fillcolor=fill,
                        fontcolor=font,
                        color=border,
                        fontname="Helvetica",
                        fontsize="10",
                    )
                    sg.edge(ent_name, attr_node_id, arrowhead="none", color="#888888")

        # ── Draw Relationships ──────────────────────────────────────────
        for idx, rel in enumerate(rels):
            rel_type = rel["rel_type"]
            label    = rel.get("label", "relates to")
            ent_a    = rel["entity_a"]
            ent_b    = rel["entity_b"]

            if rel_type == "MANY_TO_MANY":
                # M:N — draw through junction table node
                jt = rel.get("junction_table", f"{ent_a}_{ent_b}")
                if jt not in junctions:
                    dot.node(jt, label=jt, shape="diamond",
                             style="filled", fillcolor=COLOUR["junction_fill"],
                             color=COLOUR["junction_border"], fontsize="10")
                self._draw_rel_edge(dot, ent_a, jt, "M", "N", label, notation)
                self._draw_rel_edge(dot, jt, ent_b, "N", "M", "", notation)
            else:
                card_a = "1"
                card_b = "N" if rel_type == "ONE_TO_MANY" else "1"

                # Diamond node for relationship
                rel_node_id = f"rel_{idx}_{ent_a}_{ent_b}"
                dot.node(
                    rel_node_id, label=label,
                    shape="diamond", style="filled",
                    fillcolor=COLOUR["rel_fill"],
                    color=COLOUR["rel_border"],
                    fontsize="10", fontname="Helvetica",
                )
                self._draw_rel_edge(dot, ent_a, rel_node_id, card_a, "", "", notation)
                self._draw_rel_edge(dot, rel_node_id, ent_b, "", card_b, "", notation)

        # ── Draw Junction Tables (M:N) ──────────────────────────────────
        for jt_name, jt_data in junctions.items():
            if jt_name not in [n for n in dot.body]:  # avoid duplicate
                dot.node(
                    jt_name,
                    label=jt_name,
                    shape="rectangle",
                    style="filled,dashed",
                    fillcolor=COLOUR["junction_fill"],
                    color=COLOUR["junction_border"],
                    fontsize="11",
                )

        # ── Render ─────────────────────────────────────────────────────
        dot.format = fmt
        output_abs = os.path.abspath(output_path)
        rendered = dot.render(output_abs, cleanup=True, view=view)
        return rendered

    # ------------------------------------------------------------------

    def _draw_rel_edge(self, dot, src, dst, label_src, label_dst, edge_label, notation):
        """Draw a relationship edge with cardinality labels."""
        if notation == "crow":
            arrowhead = "crow" if label_dst == "N" else "tee"
            arrowtail = "crow" if label_src == "N" else "tee"
            dot.edge(src, dst, label=edge_label,
                     arrowhead=arrowhead, arrowtail=arrowtail,
                     dir="both", fontsize="9", color="#444444")
        else:
            # Chen notation: cardinality as edge labels
            xl = f"  {label_src}" if label_src else ""
            xr = f"{label_dst}  " if label_dst else ""
            dot.edge(src, dst,
                     label=f"{xl} {edge_label} {xr}".strip(),
                     arrowhead="none",
                     fontsize="11",
                     fontname="Helvetica-Bold",
                     color="#444444")
