"""
Module 6: SQL Schema Generator
Responsibility: Convert the ER model into executable CREATE TABLE SQL statements.

Supports:
  - MySQL dialect (default)
  - Standard SQL (ANSI)
  - Junction tables for M:N relationships
  - PRIMARY KEY and FOREIGN KEY constraints
"""

from typing import Optional


# Simple type inference: if attribute name suggests a type, use it
TYPE_HINTS = {
    "id":       "INT",
    "name":     "VARCHAR(100)",
    "email":    "VARCHAR(150)",
    "phone":    "VARCHAR(20)",
    "address":  "TEXT",
    "date":     "DATE",
    "time":     "TIME",
    "datetime": "DATETIME",
    "amount":   "DECIMAL(10,2)",
    "price":    "DECIMAL(10,2)",
    "salary":   "DECIMAL(10,2)",
    "age":      "INT",
    "count":    "INT",
    "number":   "INT",
    "status":   "VARCHAR(50)",
    "title":    "VARCHAR(200)",
    "description": "TEXT",
    "image":    "VARCHAR(500)",
    "url":      "VARCHAR(500)",
    "password": "VARCHAR(255)",
    "score":    "FLOAT",
    "grade":    "VARCHAR(5)",
}


class SQLSchemaGenerator:
    """
    Converts an ER model dict into SQL CREATE TABLE statements.

    Usage:
        gen = SQLSchemaGenerator()
        sql = gen.generate(er_model)
        print(sql)
    """

    def generate(self, er_model: dict, dialect: str = "mysql") -> str:
        """
        Parameters
        ----------
        er_model : dict  — from ERModelBuilder.build()
        dialect  : str   — 'mysql' or 'standard'

        Returns
        -------
        str : Complete SQL script
        """
        parts = [
            "-- ============================================================",
            "-- SQL Schema generated by Enhanced Hybrid AI DB Engine",
            "-- ============================================================",
            "",
        ]

        if dialect == "mysql":
            parts.append("SET FOREIGN_KEY_CHECKS = 0;")
            parts.append("")

        # 1. Regular entity tables (no FKs yet)
        for ent_name, ent_data in er_model["entities"].items():
            parts.append(self._create_table(ent_name, ent_data, dialect))

        # 2. Junction tables (M:N)
        for jt_name, jt_data in er_model.get("junction_tables", {}).items():
            parts.append(self._create_junction_table(jt_name, jt_data, dialect))

        if dialect == "mysql":
            parts.append("SET FOREIGN_KEY_CHECKS = 1;")

        return "\n".join(parts)

    # ------------------------------------------------------------------

    def _create_table(self, name: str, data: dict, dialect: str) -> str:
        pk      = data.get("primary_key")
        attrs   = data.get("attributes", [])
        fkeys   = data.get("foreign_keys", [])
        fk_cols = {fk["column"] for fk in fkeys}

        lines = [f"CREATE TABLE IF NOT EXISTS {name} ("]
        col_defs = []

        for attr in attrs:
            col_type = self._infer_type(attr, is_pk=(attr == pk), is_fk=(attr in fk_cols))
            nullable = "NOT NULL" if attr == pk else "DEFAULT NULL"
            col_defs.append(f"    {attr} {col_type} {nullable}")

        # Add PK that wasn't in attributes (safety net)
        attr_names = [a.lower() for a in attrs]
        if pk and pk.lower() not in attr_names:
            col_defs.insert(0, f"    {pk} INT NOT NULL AUTO_INCREMENT")

        # PRIMARY KEY constraint
        if pk:
            col_defs.append(f"    PRIMARY KEY ({pk})")

        # FOREIGN KEY constraints
        for fk in fkeys:
            ref_parts = fk["references"].split(".")
            ref_table = ref_parts[0]
            ref_col   = ref_parts[1] if len(ref_parts) > 1 else "id"
            col_defs.append(
                f"    FOREIGN KEY ({fk['column']}) "
                f"REFERENCES {ref_table}({ref_col}) ON DELETE CASCADE"
            )

        lines.append(",\n".join(col_defs))
        engine_clause = " ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;" if dialect == "mysql" else ";"
        lines.append(f"){engine_clause}")
        lines.append("")
        return "\n".join(lines)

    def _create_junction_table(self, name: str, data: dict, dialect: str) -> str:
        cols    = data.get("columns", [])
        pk_cols = data.get("primary_key", cols)
        fkeys   = data.get("foreign_keys", [])

        lines = [f"CREATE TABLE IF NOT EXISTS {name} ("]
        col_defs = []

        for col in cols:
            col_defs.append(f"    {col} INT NOT NULL")

        col_defs.append(f"    PRIMARY KEY ({', '.join(pk_cols)})")

        for fk in fkeys:
            ref_parts = fk["references"].split(".")
            ref_table = ref_parts[0]
            ref_col   = ref_parts[1] if len(ref_parts) > 1 else "id"
            col_defs.append(
                f"    FOREIGN KEY ({fk['column']}) "
                f"REFERENCES {ref_table}({ref_col}) ON DELETE CASCADE"
            )

        lines.append(",\n".join(col_defs))
        engine_clause = " ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;" if dialect == "mysql" else ";"
        lines.append(f"){engine_clause}")
        lines.append("")
        return "\n".join(lines)

    def _infer_type(self, attr_name: str, is_pk: bool, is_fk: bool) -> str:
        """Infer SQL column type from attribute name heuristics."""
        if is_pk:
            return "INT NOT NULL AUTO_INCREMENT" if "id" in attr_name.lower() else "VARCHAR(50)"
        if is_fk:
            return "INT"

        lower = attr_name.lower()
        for key, sql_type in TYPE_HINTS.items():
            if key in lower:
                return sql_type

        # Default: short string
        return "VARCHAR(100)"
